<?php

namespace AppBundle\Repository;

/**
 * WriterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WriterRepository extends \Doctrine\ORM\EntityRepository
{
}
